import type { Metadata } from "next";
import { Unbounded,Roboto } from 'next/font/google';

import AuthLayout from "@/app/components/authLayout/AuthLayout";

import "../../globals.css";

const unbounded = Unbounded({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  variable: '--font-unbounded',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "signup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${unbounded.variable} ${roboto.variable}  antialiased`}>
        <AuthLayout>
          {children}
        </AuthLayout>
      </body>
    </html>
  );
}
